
name: Publish APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (ej: v1.0.0)'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
          arguments: assembleDebug

      - name: Create GitHub Release with APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: HabitTrackerVoice ${{ github.event.inputs.tag }}
          files: app/build/outputs/apk/debug/app-debug.apk
